AuctionNew/AuctionKing/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', 'account.views.base', name="base"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    url(r'^products/', include('products.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    ) + static.static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AuctionNew/account/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    url(r'^$','account.views.base', name='base'),
    url(r'^login/$','account.views.handleLogin', name='login'),
    url(r'^signup/$','account.views.handleSignup', name='signup'),
    url(r'^activate/$', 'account.views.activateaccount', name='activate'),
    url(r'^home/$','account.views.home', name='home'),
    #url(r'^add/$','account.views.add', name='add'),
    url(r'^otherhome/$','account.views.otherhome', name='otherhome'),
    url(r'^logout/$','account.views.logoutview', name='logout'),
    url(r'^forgot_password/$', 'account.views.forgot_password', name="forgot_password"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'account.views.reset_password', name='password_reset_confirm'),
    url(r'^search/$', 'account.views.search', name = 'search'),
    url('', include('django.contrib.auth.urls', namespace='auth')),

)

AuctionNew/products/forms.py
from django import forms
from .models import *
class ProductUploadForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['Photos', 'Category', 'Title', 'BidStart','Timer']

class BidPostForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ['BidPrice']

class SearchProductForm(forms.Form):
    name = forms.CharField();

class CategorySearchForm(forms.ModelForm):
   class Meta:
      model = Product
      fields = ['Category']

AuctionNew/templates/index.html
{% extends "account/base.html" %}
{% load material_form %}
{% block title %} Auction King {% endblock %}
{% load staticfiles %}

{% block content %}
<div class="nav-wrapper" id="id_name">
<form method="GET" action="{ url 'search_product' }" enctype="multipart/form-data">
{% csrf_token %}
{% form form=form %} {% endform %}
</form>
</div>


<form method='GET' action='#' enctype="multipart/form-data">
{% csrf_token %}
{% form form=form1 %} {% endform %}
</form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'product/js/search.js' %}"> </script>
{% endblock %}